/**
 * Gwin Bookkeeping LLC — Dynamic OG Image
 *
 * Auto-generated by Next.js ImageResponse (runs on Cloudflare Edge).
 * Served at /opengraph-image and automatically wired to all social previews.
 * No image file needed — this generates a pixel-perfect 1200×630 PNG on demand.
 */

import { ImageResponse } from "next/og";

export const runtime = "edge";

export const alt =
  "Gwin Bookkeeping LLC — Clear Books. Confident Business Decisions.";

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "1200px",
          height: "630px",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #1B2A4A 0%, #2D4170 55%, #1B2A4A 100%)",
          fontFamily: "Georgia, 'Times New Roman', serif",
          position: "relative",
          overflow: "hidden",
        }}
      >
        {/* Subtle corner accents */}
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "300px",
            height: "300px",
            background:
              "radial-gradient(circle at top left, rgba(124,154,126,0.18) 0%, transparent 70%)",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: 0,
            right: 0,
            width: "350px",
            height: "350px",
            background:
              "radial-gradient(circle at bottom right, rgba(196,167,107,0.12) 0%, transparent 70%)",
          }}
        />

        {/* Logo icon box */}
        <div
          style={{
            width: "88px",
            height: "88px",
            borderRadius: "18px",
            background: "rgba(255,255,255,0.12)",
            border: "1.5px solid rgba(255,255,255,0.20)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            marginBottom: "36px",
          }}
        >
          {/* BookOpen icon (SVG paths) */}
          <svg
            width="52"
            height="52"
            viewBox="0 0 24 24"
            fill="none"
            stroke="white"
            stroke-width="1.6"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
            <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
          </svg>
        </div>

        {/* Business name */}
        <div
          style={{
            fontSize: "76px",
            fontWeight: "700",
            color: "white",
            letterSpacing: "-1.5px",
            lineHeight: "1",
            marginBottom: "10px",
          }}
        >
          Gwin Bookkeeping
        </div>

        {/* LLC subtitle */}
        <div
          style={{
            fontSize: "22px",
            color: "#7C9A7E",
            letterSpacing: "10px",
            textTransform: "uppercase",
            fontFamily: "Arial, Helvetica, sans-serif",
            fontWeight: "500",
            marginBottom: "52px",
          }}
        >
          LLC
        </div>

        {/* Gold divider */}
        <div
          style={{
            width: "72px",
            height: "3px",
            background: "#C4A76B",
            borderRadius: "2px",
            marginBottom: "44px",
          }}
        />

        {/* Tagline */}
        <div
          style={{
            fontSize: "38px",
            color: "rgba(255,255,255,0.88)",
            textAlign: "center",
            maxWidth: "820px",
            lineHeight: "1.45",
            fontStyle: "italic",
            letterSpacing: "0.2px",
          }}
        >
          Clear Books. Confident Business Decisions.
        </div>

        {/* Location badge */}
        <div
          style={{
            marginTop: "52px",
            fontSize: "18px",
            color: "#7C9A7E",
            letterSpacing: "3px",
            textTransform: "uppercase",
            fontFamily: "Arial, Helvetica, sans-serif",
            fontWeight: "500",
          }}
        >
          New Jersey · Professional Bookkeeping Services
        </div>

        {/* Bottom border accent */}
        <div
          style={{
            position: "absolute",
            bottom: "0",
            left: "0",
            right: "0",
            height: "4px",
            background:
              "linear-gradient(90deg, transparent 0%, #C4A76B 30%, #7C9A7E 70%, transparent 100%)",
          }}
        />
      </div>
    ),
    { width: 1200, height: 630 }
  );
}
